[project]
name = "moviigen"
description = "ComfyUI-MoviiGen is now available in ComfyUI, MoviiGen 1.1 is a cutting-edge video generation model that excels in cinematic aesthetics and visual quality."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["torch>=2.4.0", "torchvision>=0.19.0", "opencv-python>=4.9.0.80", "diffusers>=0.31.0", "transformers>=4.49.0", "tokenizers>=0.20.3", "accelerate>=1.1.1", "tqdm", "imageio", "easydict", "ftfy", "imageio-ffmpeg", "flash_attn", "gradio>=5.0.0", "numpy>=1.23.5,<2", "xfuser"]

[project.urls]
Repository = "https://github.com/Yuan-ManX/ComfyUI-MoviiGen"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-MoviiGen"
Icon = ""
